# Generated by Django 3.1.3 on 2020-11-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Entre com a descrição do gasto', max_length=100)),
                ('custo', models.DecimalField(decimal_places=2, help_text='Entre com o custo', max_digits=8)),
                ('data', models.DateField(help_text='Data do gasto no formato DD/MM/AAAA', verbose_name='Data do gasto')),
            ],
        ),
    ]
