# Generated by Django 3.1.3 on 2020-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='custo',
            field=models.DecimalField(decimal_places=2, help_text='Entre com o custo', max_digits=10),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='data',
            field=models.DateField(help_text='Data do gasto no formato <em>DD/MM/AAAA<em>'),
        ),
    ]
