# Generated by Django 3.1.3 on 2020-11-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_gasto_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='usuario',
        ),
    ]
